name: Deploy to fly.io
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Build amd64", "push_to_Docker_Hub"]
    types:
      - completed

jobs:
  deploy_to_fly:
    name: Deploy app to fly.io
    needs: [push_to_Docker_Hub_amd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a podtube
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          YT_TOKEN: ${{ secrets.YT_TOKEN }}
