name: Fly Deploy
on:
  push:
    branches:
      - auto_deploy_disabled
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a podtube
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          YT_TOKEN: ${{ secrets.YT_TOKEN }}
